cmake : Update cmake and apply best-practices.
Using MSVC two-phase lookup causes a compile error at line 2626 of plf_colony.
MSVC is parsing greater-than, less-than as a template parameter :
    plf_colony.h(2626): error C2760: syntax error: unexpected token 'identifier', expected ')'

[Bb]uild/ folder has been added to gitignore as it is a standard cmake build
subdirectory.

MSVC WX has been temporarily disabled since updating to C++17 and permissive-
creates many new warnings :
    slot_map.h(50): warning C4244: '=': conversion from 'Integral' to 'unsigned int', possible loss of data
    slot_map.h(50): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
    slot_map.h(50): warning C4267: '=': conversion from 'size_t' to 'uint16_t', possible loss of data
    slot_map.h(50): warning C4244: '=': conversion from 'Integral' to 'uint16_t', possible loss of data
    transcode.h(106): warning C4244: 'argument': conversion from 'int' to 'const char',possible loss of data
    transcode.h(92): warning C4244: 'argument': conversion from 'int' to 'const _Ty', possible loss of data